#!/usr/bin/env python3
# Builds the engine's shader containers offline, as a cook would: no
# shipped build compiles a shader (ADR-0029). glslangValidator compiles
# each stage under its entry name, spirv-link joins them into one module,
# spirv-val checks it for Vulkan 1.3, and Maul RHI's container writer
# (third_party/maul-rhi/tools/mrhi_container.py) writes the container with
# the same entries in WGSL, for WebGPU, and their reflection, which lands in the module's src/generated as bytes. The
# check runs none of these tools; the headers are committed, and this is
# run again whenever a source changes (D278).
#
# usage: tools/gen_shaders.py

import os
import subprocess
import sys
import tempfile

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
WRITER = os.path.join(ROOT, "third_party", "maul-rhi", "tools", "mrhi_container.py")
# Each container: its module, its name, and its stages' sources and entries,
# with any names a stage is compiled with defined.
CONTAINERS = (
    ("render", "display", (("vert", "vs"), ("frag", "fs"))),
    ("render_canvas_gpu", "sprite", (("vert", "vs"), ("frag", "fs"))),
    ("render_scene_gpu", "scene", (("vert", "vs"), ("frag", "fs"), ("frag", "fsDecaled", "DECALS"),
                                   ("cut.frag", "cut"), ("normal.frag", "normal"), ("cutnormal.frag", "cutNormal"))),
    ("render_scene_gpu", "occlusion", (("vert", "vs"), ("frag", "occlude"), ("blur.frag", "blur"))),
    ("render_scene_gpu", "reflect", (("vert", "vs"), ("frag", "march"))),
    ("render_scene_gpu", "motion", (("vert", "vs"), ("tile.frag", "tile"), ("neighbor.frag", "neighbor"), ("gather.frag", "gather"))),
    ("render_scene_gpu", "focus", (("vert", "vs"), ("prefilter.frag", "prefilter"), ("bokeh.frag", "bokeh"), ("combine.frag", "combine"))),
    ("render_scene_gpu", "contact", (("vert", "vs"), ("frag", "shade"))),
    ("render_scene_gpu", "decal", (("vert", "vs"), ("frag", "fill"))),
    ("render_scene_gpu", "probe", (("vert", "vs"), ("frag", "fill"))),
    ("render_scene_gpu", "resolve", (("vert", "vs"), ("frag", "depth"))),
    ("render_scene_gpu", "fxaa", (("vert", "vs"), ("frag", "fs"))),
    ("render_scene_gpu", "bloom", (("vert", "vs"), ("first.frag", "first"), ("down.frag", "down"), ("up.frag", "up"))),
    ("render_scene_gpu", "meter", (("histogram.comp", "histogram"), ("adapt.comp", "adapt"))),
    ("render_scene_gpu", "shadow", (("vert", "vs"), ("cut.vert", "vsCut"), ("cut.frag", "cut"))),
    ("render_scene_gpu", "sky", (("vert", "vs"), ("frag", "fs"))),
    ("render_scene_gpu", "temporal", (("vert", "vs"), ("frag", "fs"))),
    ("render_scene_gpu", "tonemap", (("vert", "vs"), ("frag", "fs"))),
    ("render_scene_gpu", "post", (("vert", "vs"), ("frag", "fs"))),
    ("render_scene_gpu", "spawn", (("comp", "spawn"), ("comp", "clear", "CLEAR"))),
    ("render_scene_gpu", "particle", (("vert", "vs"), ("frag", "fs"))),
)


def run(*command):
    result = subprocess.run(command, capture_output=True, text=True)
    if result.returncode != 0:
        sys.exit(f"{command[0]} failed:\n{result.stdout}{result.stderr}")


def build(work, shaders, name, stages):
    modules = []
    for suffix, entry, *defines in stages:
        module = os.path.join(work, f"{name}_{entry}.spv")
        run("glslangValidator", "-V", "--target-env", "vulkan1.3", *(f"-D{define}" for define in defines), "-e",
            entry, "--source-entrypoint", "main", "-o", module, os.path.join(shaders, f"{name}.{suffix}"))
        modules.append(module)
    linked = os.path.join(work, f"{name}.spv")
    run("spirv-link", "--target-env", "vulkan1.3", *modules, "-o", linked)
    run("spirv-val", "--target-env", "vulkan1.3", linked)
    container = os.path.join(work, f"{name}.mrsc")
    run(sys.executable, WRITER, linked, os.path.join(shaders, f"{name}.wgsl"), os.path.join(shaders, f"{name}.json"),
        container)
    with open(container, "rb") as file:
        return file.read()


def header(module, name, data):
    lines = [
        "#pragma once",
        "",
        f"// A shader container, generated by tools/gen_shaders.py from",
        f"// modules/{module}/shaders/{name}.*: edit the sources and run the script,",
        "// not this file.",
        "",
        "#include <array>",
        "#include <cstdint>",
        "",
        f"alignas(8) inline constexpr std::array<std::uint8_t, {len(data)}> k{name.capitalize()}Container = {{",
    ]
    for at in range(0, len(data), 12):
        lines.append("    " + " ".join(f"0x{b:02X}," for b in data[at:at + 12]))
    lines.append("};")
    return "\n".join(lines) + "\n"


def main():
    with tempfile.TemporaryDirectory() as work:
        for module, name, stages in CONTAINERS:
            shaders = os.path.join(ROOT, "modules", module, "shaders")
            data = build(work, shaders, name, stages)
            target = os.path.join(ROOT, "modules", module, "src", "generated", f"{name}_container.h")
            with open(target, "w") as file:
                file.write(header(module, name, data))
            run("clang-format-20", "-i", target)
            print(f"{target}: {len(data)} bytes")


if __name__ == "__main__":
    main()
